export const tools = [
  { href: "/tools/qr-code", title: "QR Code Generator", keywords: "qr barcode scan" },
  { href: "/tools/cgpa", title: "CGPA Calculator", keywords: "cgpa sgpa marks college" },
  { href: "/tools/currency", title: "Currency Converter", keywords: "currency exchange rate" },
  { href: "/tools/weather", title: "Weather Check", keywords: "weather temperature" },
  { href: "/tools/invoice", title: "Invoice Generator", keywords: "invoice bill receipt" },
  { href: "/tools/typing", title: "Typing Speed Test", keywords: "typing wpm speed" },
  { href: "/tools/image-compressor", title: "Image Compressor", keywords: "image compress shrink" },
  { href: "/tools/markdown-preview", title: "Markdown Preview", keywords: "markdown preview" },
  { href: "/tools/csv-json", title: "CSV JSON", keywords: "csv json convert" },
  { href: "/tools/json-formatter", title: "JSON Formatter", keywords: "json format pretty" },
  { href: "/tools/base64", title: "Base64 Encoder", keywords: "base64 encode decode" },
  { href: "/tools/hash", title: "Hash Generator", keywords: "hash sha md5" },
  { href: "/tools/uuid", title: "UUID Generator", keywords: "uuid guid random" },
  { href: "/tools/jwt", title: "JWT Decoder", keywords: "jwt token decode" },
  { href: "/tools/color", title: "Color Converter", keywords: "color hex rgb hsl" },
  { href: "/tools/contrast", title: "Contrast Checker", keywords: "contrast wcag accessibility" },
  { href: "/tools/gradient", title: "Gradient Generator", keywords: "gradient css" },
  { href: "/tools/shadows", title: "Box Shadow Generator", keywords: "shadow box css" },
  { href: "/tools/border-radius", title: "Border Radius", keywords: "border radius css" },
  { href: "/tools/case-converter", title: "Case Converter", keywords: "case upper lower title" },
  { href: "/tools/word-count", title: "Word Counter", keywords: "word count characters" },
  { href: "/tools/text-cleaner", title: "Text Cleaner", keywords: "text clean trim" },
  { href: "/tools/lorem", title: "Lorem Ipsum", keywords: "lorem ipsum placeholder" },
  { href: "/tools/password", title: "Password Generator", keywords: "password random secure" },
  { href: "/tools/strength", title: "Password Strength", keywords: "password strength check" },
  { href: "/tools/unit-converter", title: "Unit Converter", keywords: "unit convert length weight" },
];
