export const moreTools = [
  { href: "/tools/number-base", title: "Number Base", keywords: "binary octal hex decimal" },
  { href: "/tools/morse", title: "Morse Code", keywords: "morse code translate" },
  { href: "/tools/url-encode", title: "URL Encoder", keywords: "url encode decode" },
  { href: "/tools/timestamp", title: "Timestamp Converter", keywords: "timestamp unix date" },
  { href: "/tools/date-math", title: "Date Add/Subtract", keywords: "date add subtract" },
  { href: "/tools/duration", title: "Duration Calculator", keywords: "duration days between" },
  { href: "/tools/age", title: "Age Calculator", keywords: "age birthday dob" },
  { href: "/tools/emi", title: "EMI Calculator", keywords: "emi loan interest" },
  { href: "/tools/interest", title: "Compound Interest", keywords: "compound interest sip" },
  { href: "/tools/gst", title: "GST Calculator", keywords: "gst tax india" },
  { href: "/tools/discount", title: "Discount Calculator", keywords: "discount sale coupon" },
  { href: "/tools/percentage", title: "Percentage Calculator", keywords: "percentage" },
  { href: "/tools/aspect-ratio", title: "Aspect Ratio", keywords: "aspect ratio video" },
  { href: "/tools/ideal-weight", title: "Ideal Weight", keywords: "ideal weight bmi" },
  { href: "/tools/bmi", title: "BMI Calculator", keywords: "bmi body mass" },
  { href: "/tools/marks", title: "Marks Percentage", keywords: "marks percentage grade" },
  { href: "/tools/savings", title: "Savings Goal", keywords: "savings goal tracker" },
  { href: "/tools/tip-splitter", title: "Tip Splitter", keywords: "tip split bill" },
  { href: "/tools/fractions", title: "Fraction Calculator", keywords: "fraction math" },
  { href: "/tools/roman", title: "Roman Numerals", keywords: "roman numerals" },
  { href: "/tools/caesar", title: "Caesar Cipher", keywords: "caesar cipher encrypt" },
  { href: "/tools/stopwatch", title: "Stopwatch", keywords: "stopwatch timer laps" },
  { href: "/tools/countdown", title: "Countdown Timer", keywords: "countdown timer" },
  { href: "/tools/pomodoro", title: "Pomodoro Timer", keywords: "pomodoro focus" },
  { href: "/tools/metronome", title: "Metronome", keywords: "metronome bpm music" },
  { href: "/tools/randomizer", title: "Randomizer", keywords: "random dice coin" },
  { href: "/tools/team-picker", title: "Team Picker", keywords: "team random shuffle" },
  { href: "/tools/memory", title: "Memory Match", keywords: "memory game cards" },
  { href: "/tools/chart", title: "Bar Chart Maker", keywords: "bar chart graph" },
  { href: "/tools/titles", title: "Blog Title Generator", keywords: "blog title headline" },
  { href: "/tools/word-frequency", title: "Word Frequency", keywords: "word frequency count" },
  { href: "/tools/emoji", title: "Emoji Copier", keywords: "emoji copy" },
  { href: "/tools/text-diff", title: "Text Diff", keywords: "text diff compare" },
  { href: "/tools/text-pdf", title: "Text to PDF", keywords: "text pdf print" },
  { href: "/tools/placeholder", title: "SVG Placeholder", keywords: "svg placeholder image" },
  { href: "/tools/number-to-words", title: "Number to Words", keywords: "number words" },
  { href: "/tools/my-ip", title: "My IP Network", keywords: "ip address network" },
  { href: "/tools/country", title: "Country Info", keywords: "country info flag" },
  { href: "/tools/advice", title: "Random Advice", keywords: "advice random" },
  { href: "/tools/holidays", title: "Public Holidays", keywords: "holidays public" },
  { href: "/tools/dictionary", title: "Dictionary", keywords: "dictionary meaning" },
  { href: "/tools/subnet", title: "Subnet Calculator", keywords: "subnet network cidr" },
  { href: "/tools/kanban", title: "Mini Kanban", keywords: "kanban board tasks" },
  { href: "/tools/bills", title: "Bill Reminder", keywords: "bill reminder track" },
  { href: "/tools/regex", title: "Regex Tester", keywords: "regex test pattern" },
  { href: "/tools/gradient-text", title: "Gradient Text", keywords: "gradient text css" },
  { href: "/tools/csv-cleaner", title: "CSV Cleaner", keywords: "csv clean dedupe" },
  { href: "/tools/timesheet", title: "Timesheet Calculator", keywords: "timesheet hours work" },
  { href: "/tools/resume", title: "Resume Builder", keywords: "resume cv builder" },
  { href: "/tools/habits", title: "Habit Tracker", keywords: "habit tracker streak" },
  { href: "/tools/json-to-ts", title: "JSON to TypeScript", keywords: "json typescript types" },
  { href: "/tools/markdown-table", title: "CSV to Markdown", keywords: "csv markdown table" },
  { href: "/tools/image-converter", title: "Image Converter", keywords: "image convert png jpeg webp" },
  { href: "/tools/palette", title: "Palette Extractor", keywords: "palette color extract" },
  { href: "/tools/url-cleaner", title: "URL Cleaner", keywords: "url clean tracking" },
];
